# Generated by Django 2.2.12 on 2020-12-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pracodawcy',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255, unique=True)),
                ('kontakt', models.IntegerField()),
                ('data_dodania', models.DateField(blank=True, null=True)),
                ('adres', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('folder', models.IntegerField()),
            ],
            options={
                'db_table': 'Pracodawcy',
            },
        ),
    ]
